### ISSUE TITLE
Late start days don't display the last free block

### ISSUE THREAD

**Issue by Kizjkre** [CGScheduleSquad/cgs-schedule#3]
If the last block of the day is free on a late start day, the schedule ends at 2:30pm.

![Untitled](https://user-images.githubusercontent.com/24882191/66454319-61a99b80-ea1c-11e9-908e-7f7cc371618e.png)

## RELATED: 
Non-late start Wednesdays have C&C.

**Comment by liamjwang** [comment]
@Kizjkre 
1) Fixed
2) Non-late start Wednesdays have C&C in Veracross.
