### ISSUE TITLE
Assembly

### ISSUE THREAD

**Issue by KazZBodnar** [CGScheduleSquad/cgs-schedule#48]
Instead of "Assembly" on the middle school schedule, it says "free," which is incorrect.

**Comment by liamjwang** [comment]
@KazZBodnar Thanks for the report, could you post/send me your schedule link and let me know the date and time of the missing Assembly block?

**Comment by liamjwang** [comment]
Please open a new issue with details about where you encountered the issue (with link/screenshots).
